export const NEW_REMINDER_ASYNC = "NEW_REMINDER";
export const EDIT_REMINDER_ASYNC = "EDIT_REMINDER";
export const DELETE_REMINDER_ASYNC = "DELETE_REMINDER";
export const DELETE_REMINDERS_ASYNC = "DELETE_REMINDERS";
