export const NEW_REMINDER_ASYNC = "NEW_REMINDER_ASYNC";
export const EDIT_REMINDER_ASYNC = "EDIT_REMINDER_ASYNC";
export const DELETE_REMINDER_ASYNC = "DELETE_REMINDER_ASYNC";
export const DELETE_REMINDERS_ASYNC = "DELETE_REMINDERS_ASYNC";
export const GET_CURRENT_WEATHER_ASYNC = "GET_CURRENT_WEATHER_ASYNC";
export const GET_WEATHER_FORECAST_ASYNC = "GET_WEATHER_FORECAST_ASYNC";