export const NEW_REMINDER = "NEW_REMINDER";
export const EDIT_REMINDER = "EDIT_REMINDER";
export const DELETE_REMINDER = "DELETE_REMINDER";
export const DELETE_REMINDERS = "DELETE_REMINDERS";
export const SET_REMINDERS = "SET_REMINDERS";
